version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cherrye-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ilepr6o3179s"
s3_prefix = "cherrye-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableStreamARN=\"arn:aws:dynamodb:us-west-2:774012584662:table/contact-dev/stream/2021-04-19T05:05:32.742\" FromMailIdentityName=\"gemificationtest@gmail.com\" ToMailIdentityName=\"cherryesalesteam@gmail.com\""
confirm_changeset = true
